---
title: "heatmap"
author: "Minghao Gong"
date: "5/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r library}
# library
rm(list = ls())
library(tidyr)
library(dplyr)
# detach(package:plyr)
```


```{r output directory}
output_dir <- paste0("../../../../data/output/systematic-trinity-hmdb-mbank-CD-052421/","heatmap")
dir.create(output_dir)
```

```{r output pdf file name}
output_pdf_file <- paste0(output_dir,"/","heatmap.pdf")
```


## load the table
```{r load the tables, echo=FALSE}
xcms_CDexported_df <- read.csv("../../../../data/output/annotation-with-CD-exported-tables/sorted_filt_med_16.6_padj_0.05_FC_1/out_merged_matched_xcms_CDexported.csv")

MS2_annot4hm_df <- read.csv("../../../../data/output/systematic-trinity-hmdb-mbank-CD-052421/HILICpos/merge_mzCloud_wt_hmdb_mbank/collapsed_merged_trio4heatmap.csv")

```

```{r}
nrow(xcms_CDexported_df)
```


```{r}
m_df <- merge(xcms_CDexported_df,MS2_annot4hm_df, by.x = "X", by.y = "featureIdCandidate", all.x = TRUE)
```

```{r}
colnames(m_df)
```

```{r}
#' assign the FeatureID to new name as 1st step
m_df$new_name <- m_df$X  
#' assign the formula to new name as 2nd step
m_df$Formula <- gsub('\\s+', '', m_df$Formula)
m_df$new_name[m_df$Formula != ""] <- m_df$Formula[m_df$Formula != ""]
#' assign the Name from Compound Discoverer as 3rd step
m_df$new_name[m_df$Name != ""] <- m_df$Name[m_df$Name != ""]

#' assign the MS2 annotation as 4th step
m_df$new_name[!is.na(m_df$refined_name) & !m_df$refined_name == ""] <- m_df$refined_name[!is.na(m_df$refined_name) & !m_df$refined_name == ""]

#' remove duplicate new names in case there are duplicated values.
m_df$new_name[duplicated(m_df$new_name) == TRUE] = 
  paste0(m_df$new_name[duplicated(m_df$new_name) == TRUE],"_2")

row.names(m_df) <- m_df$new_name
nrow(m_df)
```
# If needed, subset the dataframe
```{r}
if(TRUE) {
  m_df <- m_df[!sapply(m_df$new_name,function(x)grepl("FT",x,fixed=TRUE)),]
}
```



```{r annotation-row table}
annot_row <- m_df %>% select(mzcloud_res,hmdb_res,mbank_res, Annotation.Source..Predicted.Compositions,Annotation.Source..Metabolika.Search,Annotation.Source..ChemSpider.Search)
row.names(annot_row) <- row.names(m_df)
colnames(annot_row) <- c("mzCloud","HMDB","massbank", "Predicted_Composition","Metabolika","ChemSpider")

#' remove all the NA to ""
annot_row[is.na(annot_row)] = ""
annot_row
```

```{r}
colnames(m_df)
```


```{r select data table}
log2HT <- m_df[,13:21] #` change accordingly
row.names(log2HT) <- row.names(m_df)
```

```{r}
# Add annotation as described above, and change the name of annotation
annotation_col = data.frame(label =  sapply(colnames(log2HT),function(x)strsplit(x,"_")[[1]][2])) #set up your treatment (class), and needs to be factor 
rownames(annotation_col) = colnames(log2HT)

annotation_col

```

```{r annotation colors}
#Specify column colors
column_colors <- paste0(c("#999999","#0000ff","#ff0000"), "60")
names(column_colors) <- c("Naive","R5pos","R5neg")
```


```{r annotation colors}
unique(annot_row$mzCloud)
unique(annot_row$HMDB)
unique(annot_row$massbank)

unique(annot_row$Predicted_Composition)
unique(annot_row$Metabolika)
unique(annot_row$ChemSpider)
```


```{r annotation colors}
mzCloud_colors <- paste0(c("#999999", "#999999","#008000","#ff0000"),"80")
names(mzCloud_colors) <- c("","No results","Full match","Invalid mass")

hmdb_colors <- paste0(c("#999999", "#999999","#008000","#ff0000","#000000"),"80")
names(hmdb_colors) <- c("","No results","Full match","Invalid mass", "PrecursorMz not given")

mbank_colors <- paste0(c("#999999", "#999999","#008000","#ff0000","#000000"),"80")
names(mbank_colors) <- c("","No results","Full match","Invalid mass","PrecursorMz not given")

Pred_Comp_colors <- paste0(c("#999999","#999999","#999999","#008000"),"80")
names(Pred_Comp_colors) <- c("","No results","No match","Full match")

Metabolika_colors <- paste0(c("#999999", "#999999","#999999","#008000","#FFF200"),"80")
names(Metabolika_colors) <- c("","No results","No match","Full match","Partial match")

ChemSpider_colors <- paste0(c("#999999", "#999999", "#999999","#008000","#FFF200"),"80")
names(ChemSpider_colors) <- c("","No match","No results","Full match","Partial match")



mycolors_l <- list(label = column_colors, 
                   mzCloud = mzCloud_colors,
                   hmdb = hmdb_colors,
                   mbank = mbank_colors)
                   # Predicted_Composition = Pred_Comp_colors,
                   # Metabolika = Metabolika_colors,
                   # ChemSpider = ChemSpider_colors)

mycolors_l

```


```{r prepare heatmap}

library(pheatmap)
library(RColorBrewer)

zscore <- function(x) {
  z <- (x - rowMeans(x))/ apply(x,1,sd)
  return(z)
}

```


```{r}
# convert NA to 0
log2HT[is.na(log2HT)==TRUE] = 0
```


```{r perform heatmap}
#numeric_input <- log2HT[,1:ncol(log2HT)]  #!

z_transformed <-zscore(log2HT)  #log(numeric_input+1,2)
z_transformed <- z_transformed[complete.cases(z_transformed), ]

#annotation_row = data.frame(GeneClass = factor(HT$pathways)) # metabolism A...
#rownames(annotation_row) = rownames(numeric_input) #e.g., Gene A, Gene B


range(z_transformed) #check the range of z_transformed

```


```{r assign breakslist}
breaksList = seq(-2.7, 2.7, 0.1) # change according to the previous output
```


```{r perform heatmap}
cell_colors <- colorRampPalette(rev(brewer.pal(n = 9, name = "RdYlBu")))(length(breaksList)) #rev()


# mat_breaks <- seq(min(z_transformed), max(z_transformed), length.out = 1)



pdf(file=output_pdf_file, width =30,height=100, paper = "special",onefile=FALSE)
par(mar = c(5,15,5,15))
# Either z_transformed or HT #
pheatmap(z_transformed, cluster_rows = TRUE, show_rownames = TRUE, cluster_cols = TRUE, 
         annotation_col = annotation_col, annotation_row = annot_row, annotation_colors = mycolors_l, clustering_method = "complete", breaks = breaksList, 
         color = cell_colors, cellwidth = 10, cellheight = 10) 
#HT or z_transformed; col, cluster_rows,cluster_cols; 

#Reset_it
dev.off()
```

```{r}
write.csv(m_df,paste0(output_dir,"hm_merged_tab.csv"))
```

