---
title: "Rafi_exhausted_CD8_xcms_dataframe_reorg"
author: Minghao Gong
date: 05/23/2021 
modification sources: modified from the counterpart of RPneg notebook
output: html_document
note: reorganization of data for heatmap
---


# Load the libraries

```{r setup, cache = FALSE}
knitr::opts_chunk$set(error = TRUE)

#knitr::opts_chunk$set(eval = FALSE)
```

```{r, include=FALSE}
rm(list = ls())
library(xcms)
library(RColorBrewer)
library(pander)
library(magrittr)
library(pheatmap)
library(SummarizedExperiment)
library(dplyr)
library(tidyr)
library(ggpubr)
library(ggplot2)
getwd()
```


```{r}
output_dir = "../../../../data/output/manual_compiled_MS2_mzCloud_mbank_hmdb_res"
dir.create(output_dir)
```

```{r read the table}
df <- read.csv("../../../../data/input/manual_compiled_MS2_mzCloud_mbank_hmdb_res/tables/HILICpos_manual_input_mzCloud_mbank_hmdb_matched_spectra_in_Rafi_Sign_list.csv")
colnames(df)
```

```{r}

```


```{r}
detach(package:plyr) # This is critical to avoid single-row summary which is used in plyr
agg_df <- df %>% filter(likely2beTrue == "yes") %>% group_by(X) %>% summarize_all(paste(annotation, collapse = ";"))  
# pathway_collapsed = paste(annotation, collapse = ";")
dim(agg_df)
dim(agg_df)
```
```{r}
# TODO: summarize multiple columns
# Now I just manual do it for this time.
```

