---
title: "XIC checking of the FT"
author: "Minghao Gong"
date: "06/02/2021"
output: html_document
note: This is a R markdown file to check XIC of the feature FTXXX
---

## Clean up and remove existed files
```{r, include=FALSE}
rm(list = ls())

library(xcms)
library(RColorBrewer)
library(pander)
library(magrittr)
library(pheatmap)
library(SummarizedExperiment)
library(dplyr)
library(tidyr)
library(ggpubr)
library(ggplot2)
```

## Load the xdata object and set the output_directory

```{r}

getwd()

if(TRUE) {
  # When you want to reexamine certain peaks, and this provides the entry to reload xdata object.
  raw_data <- readRDS("../../../../data/output/v0412_fix/HILICpos/xcms/cor_wt_binSize0.005/raw_data.rds")
  output_dir_XIC <- "../../../../data/output/manual_compiled_MS2_mzCloud_mbank_hmdb_res/incl_list_XICplots/"
  dir.create(output_dir_XIC)
}

```


## load the inclusion list previously generated.

```{r annotation dataframe}
annot_df <- read.csv("../../../../data/output/manual_compiled_MS2_mzCloud_mbank_hmdb_res/reorg_manual_this_time/summarized_HILICpos_manual_input_mzCloud_mbank_hmdb_matched_spectra_in_Rafi_Sign_list.csv", header = TRUE)
colnames(annot_df)
```

```{r load inclusion list}
incl_l <- read.csv("../../../../data/output/MS2_Spectra_massbank_match_05152021/HILICpos/Significant_list/sorted_filt_med_16.6_padj_0.05_FC_1_ttest_R5posvsR5neg.csv", header = TRUE)
colnames(incl_l)
```


```{r merge inclusion list and MS2-matched annotation table}
m_df <- merge(incl_l,annot_df, on = "X")
colnames(m_df)
```


## Check the raw_data
```{r}
isS4(raw_data)
slotNames(raw_data)
raw_data$sample_group
raw_data$sample_name

```
```{r}
m_df[,c("mzmed","rtmax","rtmin","precursorMz")]
```

```{r}
mzr_l <- m_df$mzmed
rt_min_l <- m_df$rtmin
rt_max_l <- m_df$rtmax
```


# XIC plot of internal standard
```{r message=FALSE, warning=FALSE, include=FALSE}
# Still look at the 
ppm = 10 # I can play around and find out that 50 do make things lousy.

output_dir_XIC_ppm <-  paste0(output_dir_XIC,"ppm_",ppm,"/")

dir.create(output_dir_XIC_ppm)

#' a function to translate ppm to mz_diff
ppm2mz_diff <- function(ppm,mz) {
  return(ppm/(10^6) * mz )
}

for (j in (1:length(mzr_l))) { #test using 2
  mz = mzr_l[j]
  mzr <- c(mz-ppm2mz_diff(mz,ppm), mz+ppm2mz_diff(mz,ppm)) #base on the previous 
  rtr = c(rt_min_l[j]-5,rt_max_l[j]+5) 
  
  if(TRUE) {
  pdf(paste0(output_dir_XIC_ppm,m_df$name[j],"_",m_df$precursorMz[j],"_",mz,"_ppm_",ppm,".pdf"))}
    par(mar= c(3,7,3,3), mfrow = c(3, 2)) 
    try(raw_data %>%
        filterFile(c(1:12)) %>% # may subject to changes
        filterRt(rt = rtr) %>%
        filterMz(mz = mzr) %>%
        plot(type = "XIC")
    )
    dev.off()
  
  
}

```

