version: '3.9'
services:
  R-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rafi-r-notebook
    image: gongm/rafi-r-notebook
    ports:
      - '8888:8888'
    volumes:
      - ../../:/home/jovyan/
      

